# Generated by Django 4.0.6 on 2022-08-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['title'], name='title_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['id'], name='image_id_idx'),
        ),
    ]
