# Generated by Django 4.0.6 on 2022-08-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_title_idx_image_image_id_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
