# Generated by Django 4.0.6 on 2022-08-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
