# Generated by Django 4.0.6 on 2022-08-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
