# Generated by Django 4.0.6 on 2022-07-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_imagecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='imagecategory',
            old_name='id_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='imagecategory',
            old_name='id_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(through='api.ImageCategory', to='api.category'),
        ),
    ]
