# Generated by Django 4.0.6 on 2022-07-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_id_user_image_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('VIDEOGAMES', 'Videogames'), ('ANIME', 'Anime'), ('MUSIC', 'Music'), ('CARTOONS', 'Cartoons')], max_length=15),
        ),
    ]
