# Generated by Django 4.0.6 on 2022-07-12 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_category_category_category_n'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_n',
            new_name='category',
        ),
    ]
